# Use an official Node.js runtime as a base image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/index

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install express ws cors path electron

# Copy the application files to the working directory
COPY public ./public
COPY index.js index.js
COPY renderer.js renderer.js
COPY my-electron-app ./my-electron-app 
# Expose the port the app runs on
EXPOSE 5500

# Define the command to run your application
CMD ["npm", "index.js"]
